apiVersion: v1
kind: Service
metadata:
  name: gemma-2b-service
spec:
  type: LoadBalancer
  selector:
    # This must match the 'app' label in your deployment's template metadata.
    app: gemma-2b-vllm
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000